version: '2'
services:
  db:
    image: postgres:11
    networks:
      - odoo
    ports:
      - "5432:5432"
    container_name: postgres11
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo13:
    build: .
    container_name: odoo13
    networks:
      - odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./custom_addons:/mnt/custom-addons
      - ./enterprise:/mnt/enterprise-addons
      - ./workspace:/mnt/company-addons
      - ./etc:/etc/odoo
      - ./requirements.txt:/usr/local/bin/requirements.txt
    restart: always   
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    networks:
      - odoo
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin 
      - PGADMIN_LISTEN_PORT=80
    ports: 
      - "1234:80"
    links:
      - "db:pgsql-server"
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    restart: always        # run as a service

networks:
  odoo:
    driver: bridge