from . import studio_mixin
from . import base_automation
from . import mail_template
from . import ir_actions_act_window
from . import ir_actions_report
from . import ir_actions_server
from . import ir_filters
from . import ir_model
from . import ir_model_data
from . import ir_module_module
from . import ir_rule
from . import ir_ui_menu
from . import ir_ui_view
from . import res_groups
from . import res_company
from . import ir_qweb
from . import report_paperformat
